name: ðŸ“ž Release Please

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: src

jobs:
  # Creates Release PRs then, once merged, the same job will:
  # - Tag the full version (hence the following version tag job for short tag names)
  # - Create the release for this version
  # -
  release-please:
    name: âœ¨ Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write # releases, tags
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      pr_created: ${{ steps.release.outputs.release_created }}
      v_major: ${{ steps.release.outputs.major }}
      v_minor: ${{ steps.release.outputs.minor }}
      v_patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: âœ¨ Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please/config.json
          manifest-file: release-please/manifest.json

  tag-commits:
    name: ðŸ·ï¸ Tag Commits
    runs-on: ubuntu-latest
    permissions:
      contents: write # releases, tags
    needs:
      - release-please
    if: ${{ needs.release-please.outputs.version }}
    env:
      V_MAJOR: ${{ needs.release-please.outputs.major }}
      V_MINOR: ${{ needs.release-please.outputs.minor }}
      V_PATCH: ${{ needs.release-please.outputs.patch }}
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v4
      - run: |
          echo "Major version: ${{ needs.release-please.outputs.v_major }}"
          echo "Minor version: ${{ needs.release-please.outputs.v_minor }}"
          echo "Patch version: ${{ needs.release-please.outputs.v_patch }}"
          echo "env Major version: ${{ env.V_MAJOR }}"
          echo "env Minor version: ${{ env.V_MINOR }}"
          echo "env Patch version: ${{ env.V_PATCH }}"

  publish:
    name: ðŸ“¦ Publish to NuGet
    runs-on: ubuntu-latest
    permissions:
      contents: write # releases, tags
    needs:
      - release-please
      - tag-commits
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: ðŸ›’ Checkout
        uses: actions/checkout@v4
      - name: ðŸŸ£ Setup .NET
        uses: actions/setup-dotnet@v4
      - name: ðŸ“¦ Pack
        run: >
          dotnet pack
          --configuration Release
      - name: ðŸš€ Push to Nuget
        run: >
          dotnet nuget push
          "nuget/*.nupkg"
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate
      - name: ðŸš€ Push to Github Packages
        run: >
          dotnet nuget push
          "nuget/*.nupkg"
          --api-key ${{ secrets.GITHUB_TOKEN }}
          --source https://nuget.pkg.github.com/Fonts.Avalonia/index.json
          --skip-duplicate
